# Generated by Django 2.2.3 on 2019-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190719_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(default='none', help_text='The language this snippet is written in.', max_length=50),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
