# Generated by Django 2.2.3 on 2019-07-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190720_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='times_copied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
